---
- name: Install the repository RPM
  yum_repository:
    name: mongodb-org-{{mongodb_ver}}
    description: mongodb {{mongodb_ver}}
    file: mongodb-org-{{mongodb_ver}}
    baseurl: https://repo.mongodb.org/yum/redhat/$releasever/mongodb-org/{{mongodb_ver}}/x86_64/
    gpgkey: https://www.mongodb.org/static/pgp/server-{{mongodb_ver}}.asc
    gpgcheck: yes
    enabled: yes

- name: Install MongoDB{{mongodb_ver}}
  yum: 
    name: [mongodb-org]
    state: latest


- name: Create Databases Directory
  file:
    path: /data/mongo
    state: directory
    owner: mongod
    group: mongod
